version: '3.4'

services:
  db:
    build:
      context: .
      dockerfile: db/postgres.Dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: events
      POSTGRES_PASSWORD: postgres
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      TZ: Europe/Stockholm
      PGTZ: Europe/Stockholm
    volumes:
      - dbdata:/var/lib/postgresql/data
      - .:/repo
      - ~/.sqitch:/root/.sqitch
    working_dir: /repo

  server:
    image: axelulmestig/organize.party
    ports:
      - "8081:8081"
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
    env_file: .env

  production:
    image: axelulmestig/organize.party:latest
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
    env_file: .env

volumes:
  dbdata:
