cabal-version:      3.14

name:               op-worker
version:            0.1
license:            BSD-3-Clause
license-file:       ../LICENSE
author:             Axel Ulmestig
maintainer:         axel.ulmestig@gmail.com
build-type:         Simple

common warnings
    ghc-options: -Wall

executable op-worker
    import:           warnings
    main-is:          Main.hs
    other-modules:    Op.Worker.Job
                    , Op.Worker.JobLogistics
                    , Op.Worker.Jobs.Debug
                    , Op.Worker.Jobs.PollS3FileUpload
                    , Op.Worker.Jobs.ProcessAwsSnsWebhookMessage
                    , Op.Worker.Jobs.SendEmail
    build-depends:    base ^>=4.19.2.0
                    , aeson
                    , aeson-qq
                    , bytestring
                    , every
                    , hasql
                    , hasql-notifications
                    , lens-aeson
                    , mime-mail
                    , modern-uri
                    , mtl
                    , network
                    , op-db
                    , req
                    , resource-pool
                    , stm
                    , string-interpolate
                    , text
                    , unix
                    , unliftio
                    , utf8-string
                    , uuid
                    , vector
                    , rio
                    , smtp-mail
    hs-source-dirs:   src
    default-language: GHC2021
    ghc-options:      -threaded -rtsopts "-with-rtsopts=-N -A64m" -O2

    default-extensions:
                      BlockArguments
                    , DataKinds
                    , DeriveGeneric
                    , FlexibleContexts
                    , FlexibleInstances
                    , MultiParamTypeClasses
                    , NamedFieldPuns
                    , OverloadedRecordDot
                    , OverloadedStrings
                    , RecordWildCards
                    , QuasiQuotes
                    , TypeOperators
                    , TemplateHaskell
                    , NoImplicitPrelude
